CREATE TABLE GeneralType (
  	TYPE_ID int  NOT NULL PRIMARY KEY,
	TYPE_NAME char(70)  NOT NULL
);

CREATE TABLE AttackType (
  	ATTACK_ID int NOT NULL PRIMARY KEY,
	TYPE_ID int NOT NULL,
	CONSTRAINT FK_Typeid FOREIGN KEY (TYPE_ID) 
		REFERENCES GeneralType(TYPE_ID));

CREATE TABLE Country (
  	COUNTRY_ID int NOT NULL PRIMARY KEY,
	COUNTRY_NAME char(70)  NOT NULL
);


CREATE TABLE Place (
  	PLACE_ID char(10) NOT NULL PRIMARY KEY,
	PLACE_NAME char(70) NOT NULL,
	COUNTRY_ID int NOT NULL,
	CONSTRAINT FK_Country FOREIGN KEY (COUNTRY_ID) 
		REFERENCES Country(COUNTRY_ID)
);


CREATE TABLE AttackBase (
  	ATTACK_ID int NOT NULL PRIMARY KEY,
	PLACE_ID char(10) NOT NULL,
	ATTACK_DATE date NOT NULL,
	CONSTRAINT FK_Placeid FOREIGN KEY (PLACE_ID) 
		REFERENCES Place(PLACE_ID)
);


